version: "3.3"


services:
  fastapi:
    image: 'fastapi_test'
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command:
      - uvicorn
      - app:app
      - --host
      - 0.0.0.0

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - postgres
      interval: 10s
      timeout: 2s
      retries: 5
